### ISSUE TITLE
No sound on Arch/Wine 7.0

### ISSUE THREAD

**Issue by celtichawk** [RastislavKish/nvda2speechd#1]
I've been poking at this and following the directions in the readme, however

I am running into two issues.

1. If I run it as directed, I get no sounds
2. If I try setting the environment variable, I get no identifier error in the terminal

**Comment by RastislavKish** [comment]
@celtichawk thanks for filling out the issue!
We have discussed this topic on the Blinux mailing list, and tried several solutions.
The question is, were you eventually able to get it working? Is the issue still actual?
The project also got few updates in response to #2 and #3, that should considerably improve the compilation process.

**Comment by RastislavKish** [comment]
@celtichawk since this issue has not been active in a while, I'm considering it to be resolved. If that's not the case and your problems persist, please feel free to reviwe it, or open a new-one.
